# Site settings
title: 暗梅幽闻花
email: anypossible.w@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 186470 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Dr. anypossible.w
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/anyispossible
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/anypossiblew
  - title: bitbucket 
    url: http://bitbucket.org/anypossiblew
  - title: github
    url: http://github.com/anypossiblew

# Postal address (add as many lines as necessary)
address:
  - line: 上海市虹口区
  - line: 广粤路53弄 4号402室
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
